name: Plugina
main: com.github.odin8472.Plugina.Plugina
version: 1
commands:
   basic:
      description: This is a demo command.
      usage: /<command> [player]
//      permission: Plugina.basic
//      permission-message: You don't have <permission>
